### ISSUE TITLE
How to build this repository to apk 

### ISSUE THREAD

**Issue by batata004** [VolcanoMobile/fluidsynth#15]
Hi,

I read the documentation but I cant find the instructions on how to build the code of this repository to create the apk file to be installed on android smartphones.

On play store there is the FluidSynth app and I would like to build that exactly app but I will do some small changes in the code to better suit my needs. However I first need to understand how to build the FluidSynth android app (probably using Android Studio) but I cant fine instrucstions on how to do it.

Could you please point me in the right direction?

**Comment by loki666** [comment]
this repository is not meant to build an application APK
it's only a modified version of FluidSynth library stripped of all the drivers.
an application still needs to pump the audio out of FluidSynth and feed it to an Android audio driver ie: OpenSL/AAudio/Oboe/SoundTrack
