### ISSUE TITLE
Allow the user to select the channel in the banks

### ISSUE THREAD

**Issue by batata004** [VolcanoMobile/fluidsynth#16]
Hi, when I open Fluidsynth on android I can assign to each line a soundfont which will only be played on a specific channel.

However frequently I need to play more than one instrument together when I press a key on my midi controller. However my midi controller only sends the key presses to a specific channel that I configured in it. So, if I configure it to send the notes to channel 3 then Fluidsynth will only play the instrument loaded in the third line. But what if I need to play 2 different instruments? If I place them on different lines, each one will be assigned to a different channel...

Is this possible with the current implementation or do you know any android app that allows me to do that?

Thank you and congratulations for this amazing work.!

**Comment by loki666** [comment]
This is not a FluidSynth bug, that's how FluidSynth works
Now, an Application which integrates this library (like FluidSynth MIDI Synthethizer) could allow the user to "route" the MIDI events coming from a MIDI controller, to different MIDI Channels.
This is out of scope of the library which is just a fork of upstream FluidSynth

**Comment by batata004** [comment]
@loki666 would you please recommend an app that rountes MIDI to different channels? I tried building one using the ndk examples in Android studio but I got in too many errors. Could you kindly point me in the right direction?
