### ISSUE TITLE
How do I hire someone to compile the apk

### ISSUE THREAD

**Issue by batata004** [VolcanoMobile/fluidsynth#17]
Hi, I am looking for someone who can compile the apk which I can pay. I am having lots of problems trying to compile this repository into an apk. How do I find someone who can compile it and make a small change (it's really small, I can tell later if there is anyone interested).

**Comment by loki666** [comment]
this repository is not meant to build an application APK
it's only a modified version of FluidSynth library stripped of all the drivers.
an application still needs to pump the audio out of FluidSynth and feed it to an Android audio driver ie: OpenSL/AAudio/Oboe/SoundTrack
